added missing include in GLES renderer for CSingleLock
Closes: Trac ticket #11173

Error before the patch:
LinuxRendererGLES.cpp: In member function 'void CLinuxRendererGLES::LoadPlane(CLinuxRendererGLES::YUVPLANE&, int, unsigned int, unsigned int, unsigned int, int, void*)':
LinuxRendererGLES.cpp:307: warning: comparison between signed and unsigned integer expressions
LinuxRendererGLES.cpp:312: warning: comparison between signed and unsigned integer expressions
LinuxRendererGLES.cpp:318: warning: unused variable 'pixelData'
LinuxRendererGLES.cpp: In member function 'virtual unsigned int CLinuxRendererGLES::PreInit()':
LinuxRendererGLES.cpp:637: error: 'CSingleLock' was not declared in this scope
LinuxRendererGLES.cpp:637: error: expected `;' before 'lock'
LinuxRendererGLES.cpp: In member function 'virtual void CLinuxRendererGLES::UnInit()':
LinuxRendererGLES.cpp:805: error: 'CSingleLock' was not declared in this scope
LinuxRendererGLES.cpp:805: error: expected `;' before 'lock'
make[1]: *** [LinuxRendererGLES.o] Error 1